name: e_book
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # firebase packages
  firebase_core: ^2.27.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  # Others packages
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.7
  syncfusion_flutter_pdfviewer: ^23.1.36
  lottie: ^2.6.0
  google_sign_in: ^6.1.5
  fluttertoast: ^8.2.2
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  uuid: ^3.0.7
  equatable: ^2.0.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Add assets of your application
  assets:
    - assets/Images/
    - assets/Icons/
    - assets/Animation/

  #  Add fonts of your application
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600