// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1aEGALxrZSwXUhtclvYGQ1iyNhiNdWcg',
    appId: '1:88921679213:web:30fc77a13c606896246664',
    messagingSenderId: '88921679213',
    projectId: 'ebook-e542a',
    authDomain: 'ebook-e542a.firebaseapp.com',
    storageBucket: 'ebook-e542a.appspot.com',
    measurementId: 'G-722Q2ZXDF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRvjeJsnnu9gyN3_jBGoxAYzxJOG-jzQ',
    appId: '1:88921679213:android:8ce532ac11828b16246664',
    messagingSenderId: '88921679213',
    projectId: 'ebook-e542a',
    storageBucket: 'ebook-e542a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_ty-NVYdEDZiNZN5tZLsMyt1qTuX6PQ',
    appId: '1:88921679213:ios:1879a0823715cf3d246664',
    messagingSenderId: '88921679213',
    projectId: 'ebook-e542a',
    storageBucket: 'ebook-e542a.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_ty-NVYdEDZiNZN5tZLsMyt1qTuX6PQ',
    appId: '1:88921679213:ios:f16949183b3a2423246664',
    messagingSenderId: '88921679213',
    projectId: 'ebook-e542a',
    storageBucket: 'ebook-e542a.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
